services:
  postgres:
    container_name: manager_task_db
    image: postgres:latest
    environment:
        POSTGRES_DB: manager_task_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: qPz8am91
    ports:
        - "5432:5432"
    volumes:
        - postgres-data:/usr/local/pgsql

    

volumes:
    postgres-data: